sonar.projectKey=hsc00_trust-vote-ai
sonar.organization=hsc00
sonar.projectName=TrustVote AI
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/node_modules/**, **/dist/**, **/*.spec.ts, packages/docs/**, packages/backend/src/main.ts
sonar.tests=packages
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8